---
# tasks file for app
    - name: Show info about the env this host belongs to
      debug:
        msg: "This host is in {{ env }} environment!!!"

    - name: Add unit file for Puma
      copy:
       # src: roles/app/files/puma.service
        src: /home/dom/Guzzel_infra/ansible/roles/app/files/puma.service
        dest: /etc/systemd/system/puma.service
      notify: reload puma

    - name: Add config for DB connection
      template:
        src: /home/dom/Guzzel_infra/ansible/roles/app/templates/db_config.j2
        #src: roles/app/templates/db_config.j2
        dest: /home/ubuntu/db_config
        owner: ubuntu
        group: ubuntu

    - name: enable puma
      systemd: name=puma enabled=yes
